[project]
name = "GhostDayz"
description = "Make your web services secure by default !"
version = "1.4.3"
authors = [
    { name = "ghostdayz", email = "anonymousarchives@outlook.com" }
]

[tool.black]
exclude = '''
/(
  | \.git
  | src/deps/src
  | src/common/core/modsecurity
  | env
)/
'''
